"""Shared fixtures for the SimulationOutput golden test.

Kept in its own module so the golden snapshot can be regenerated by a script without importing
the test module. Regenerate deliberately with:

    python -m backend.tests.golden_support --regenerate

A golden test is only worth having if regenerating is a conscious act; if it were automatic the
snapshot would silently absorb regressions.
"""

from __future__ import annotations

import json
import pathlib
from typing import Dict, List

from backend.app.engine import assemble
from backend.app.schemas import (
    GateSelection,
    LongLeadSelection,
    PackageSelection,
    RaisedDecisionPoint,
    StageReasoning,
)
from backend.app.simulator import build_simulation_output

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
GOLDEN_PATH = pathlib.Path(__file__).parent / 'golden' / 'simulation_output.json'

#: The confirmed brief for the seed project — the output of intake, as sample_brief.json
#: documents it. Loaded from the fixture so the golden run uses the real seed brief.
SEED_BRIEF_PATH = REPO_ROOT / 'sample_brief.json'


def seed_brief() -> Dict:
    raw = json.loads(SEED_BRIEF_PATH.read_text(encoding='utf-8'))
    return {k: v for k, v in raw.items() if not k.startswith('_') and k != 'field_provenance'}


#: The stages the golden run walks, and the fragnet each selects. Restricted to stages that have
#: library fragnets, so the golden output exercises real instancing rather than empty stages.
GOLDEN_WALK = ['design', 'procurement', 'substructure', 'mep_power', 'mep_cooling',
               'commissioning']

STAGE_FRAGNETS = {
    'substructure': 'frag.substructure.raft',
    'mep_power': 'frag.mep.power_train',
    'mep_cooling': 'frag.mep.cooling',
    'commissioning': 'frag.commissioning.ladder',
}

#: The forks the seed brief should surface, and where. Derived from the brief itself:
#: - gensets are owner-furnished (dp.ofe)
#: - the HT substation is on our scope and energisation is the client's critical concern
#:   (dp.grid_position)
#: - no lead time is confirmed by a PO anywhere in the brief (dp.long_lead_unconfirmed)
#: - the statutory pathway has not been confirmed by a compliance team (dp.city_pathway_unconfirmed)
EXPECTED_FORKS = {
    'design': ['dp.tier_topology'],
    'procurement': ['dp.ofe', 'dp.grid_position', 'dp.long_lead_unconfirmed'],
}

SEED_ANSWERS = {
    'dp.tier_topology': 'N+1 confirmed on electrical and cooling',
    'dp.ofe': 'Owner-furnished under the client Cummins framework',
    'dp.grid_position': 'Build dedicated substation - HT substation is on our scope',
    'dp.long_lead_unconfirmed': 'Not confirmed - use library estimate and flag',
}


def _pkg(fragnet_id: str) -> PackageSelection:
    return PackageSelection(
        fragnet_id=fragnet_id, why=f'{fragnet_id} is the applicable package for this stage',
        confidence=0.9, effective_confidence=0.5, sources=['corpus:1#0'],
        unverified_dependencies=[fragnet_id],
    )


def _fork(decision_id: str) -> RaisedDecisionPoint:
    from backend.app.libraries import load_library

    entry = next(d for d in load_library('decision_points')['entries']
                 if d['id'] == decision_id)
    return RaisedDecisionPoint(
        decision_point_id=decision_id, question=entry['question'],
        why_stuck=entry['why_stuck'], options=entry['options'], impact=entry['impact'],
        blocking=True, detection='curated',
    )


class GoldenReasoner:
    """A fixed stand-in for reason_stage.

    Deliberately not a recording of a live run: the golden test exists to pin the SHAPE of the
    output and the fork behaviour, and a captured LLM response would make it re-fail on every
    harmless wording change. The forks it raises come from the real decision-point library.
    """

    def __call__(self, stage, brief, *, session=None, decisions=None, adapter=None, **kw):
        answered = {d['id'] for d in (decisions or [])}
        fragnet = STAGE_FRAGNETS.get(stage)
        forks = [f for f in EXPECTED_FORKS.get(stage, []) if f not in answered]
        return StageReasoning(
            stage=stage,
            packages=[_pkg(fragnet)] if fragnet else [],
            gates=[
                GateSelection(
                    gate_id='path.nm.peso_hsd', why='Bulk HSD storage for the generators',
                    confidence=0.8, effective_confidence=0.5,
                    unverified_dependencies=['path.nm.peso_hsd'],
                )
            ] if stage == 'mep_power' else [],
            long_lead=[
                LongLeadSelection(
                    lead_id='lead.transformer_hv', why='Drives energisation and therefore RFS',
                    confidence=0.8, effective_confidence=0.5,
                    unverified_dependencies=['lead.transformer_hv'],
                )
            ] if stage == 'procurement' else [],
            decision_points=[_fork(f) for f in forks],
            library_version='v1', corpus_version='v1', prompt_version='v1',
        )


def build_golden_output():
    """Drive the full walk to completion and project the SimulationOutput. Deterministic."""
    from backend.app.simulator import DecisionAnswer, Simulator

    import backend.app.simulator.runner as runner_module

    original = runner_module.reason_stage
    runner_module.reason_stage = GoldenReasoner()
    try:
        simulator = Simulator(seed_brief(), run_id='golden', stages=GOLDEN_WALK)
        for _ in range(10):
            list(simulator.run())
            if not simulator.is_halted:
                break
            for decision_id in sorted(simulator.state.pending_decisions):
                simulator.answer(DecisionAnswer(
                    decision_point_id=decision_id,
                    answer=SEED_ANSWERS.get(decision_id, 'Confirmed'),
                ))
        return simulator, simulator.output(questions=['Confirm the client organisation name.'])
    finally:
        runner_module.reason_stage = original


def load_golden() -> Dict:
    return json.loads(GOLDEN_PATH.read_text(encoding='utf-8'))


def write_golden() -> pathlib.Path:
    _, output = build_golden_output()
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(
        json.dumps(output.model_dump(), indent=2, sort_keys=True, ensure_ascii=False) + '\n',
        encoding='utf-8',
    )
    return GOLDEN_PATH


if __name__ == '__main__':
    import sys

    if '--regenerate' in sys.argv:
        path = write_golden()
        print(f'wrote {path}')
    else:
        print(__doc__)
